analyzer:
  errors:
    todo: ignore
    dead_code: ignore
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    avoid_print: ignore
    use_key_in_widget_constructors: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - valid_regexps
