import 'package:equatable/equatable.dart';

import 'job_enums.dart';

/// Analysis report entity - generated by job execution
class AnalysisReport extends Equatable {
  final String id;
  final String jobId;
  final String jobName;
  final DateTime createdAt;
  final String summaryTitle;
  final String summaryText;
  final RiskLevel riskLevel;
  final List<String> highlights;

  const AnalysisReport({
    required this.id,
    required this.jobId,
    required this.jobName,
    required this.createdAt,
    required this.summaryTitle,
    required this.summaryText,
    required this.riskLevel,
    required this.highlights,
  });

  AnalysisReport copyWith({
    String? id,
    String? jobId,
    String? jobName,
    DateTime? createdAt,
    String? summaryTitle,
    String? summaryText,
    RiskLevel? riskLevel,
    List<String>? highlights,
  }) {
    return AnalysisReport(
      id: id ?? this.id,
      jobId: jobId ?? this.jobId,
      jobName: jobName ?? this.jobName,
      createdAt: createdAt ?? this.createdAt,
      summaryTitle: summaryTitle ?? this.summaryTitle,
      summaryText: summaryText ?? this.summaryText,
      riskLevel: riskLevel ?? this.riskLevel,
      highlights: highlights ?? this.highlights,
    );
  }

  @override
  List<Object?> get props => [
        id,
        jobId,
        jobName,
        createdAt,
        summaryTitle,
        summaryText,
        riskLevel,
        highlights,
      ];
}
