import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';

/// Individual insight generated by the analysis explainer
class ArgusInsight extends Equatable {
  final String title;
  final String body; // Changed from 'description' to 'body' per spec
  final InsightSeverity severity;
  final IconData icon;

  const ArgusInsight({
    required this.title,
    required this.body,
    required this.severity,
    required this.icon,
  });

  @override
  List<Object?> get props => [title, body, severity, icon];
}

/// Severity level for insights
enum InsightSeverity {
  positive, // Green - Good news
  neutral, // Yellow - Informational
  caution, // Orange - Watch out
  negative, // Red - Warning
}

extension InsightSeverityExtension on InsightSeverity {
  Color get color {
    switch (this) {
      case InsightSeverity.positive:
        return Colors.green;
      case InsightSeverity.neutral:
        return Colors.blue;
      case InsightSeverity.caution:
        return Colors.orange;
      case InsightSeverity.negative:
        return Colors.red;
    }
  }

  String get label {
    switch (this) {
      case InsightSeverity.positive:
        return 'Olumlu';
      case InsightSeverity.neutral:
        return 'Bilgi';
      case InsightSeverity.caution:
        return 'Dikkat';
      case InsightSeverity.negative:
        return 'Uyarı';
    }
  }
}
